name: Deployment Development Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types:
      - opened
      - synchronize

jobs:
  deploy_dev:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalar dependencias
        run: npm install --no-audit --no-found --no-optional
      - name: Instalar linter
        run: npm install @typescript-eslint/eslint-plugin@latest eslint-plugin-react@latest --save-dev
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Ejecutar Tests
        run: npm run test
      - name: Mostrar Coverage
        run: npm run coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
      - name: Install Vercel CLI
        if: ${{github.event_name === 'push'}}
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: ${{github.event_name === 'push'}}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: ${{github.event_name === 'push'}}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: ${{github.event_name === 'push'}}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
