name: Deployment Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalar dependencias
        run: npm install --no-audit --no-found --no-optional
      - name: Instalar linter
        run: npm install @typescript-eslint/eslint-plugin@latest eslint-plugin-react@latest --save-dev
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Ejecutar Tests
        run: npm run test
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy to Vercel
      #   uses: ngduc/vercel-deploy-action@master
      #   with:
      #     github-token: ${{ secrets.GH_PAT }}
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required