name: Pull Request to Development Pipeline

on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - synchronize

jobs:
  deploy_dev:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalar dependencias
        run: npm install --no-audit --no-found --no-optional
      - name: Instalar linter
        run: npm install @typescript-eslint/eslint-plugin@latest eslint-plugin-react@latest --save-dev
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Ejecutar Tests
        run: npm run test
      - name: Mostrar Coverage
        run: npm run coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown