name: Automatic Revert

on:
  issue_comment:
    types:
      - created

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, '/revert')

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Git
        run: git config --global --add safe.directory /github/workspace
      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
