name: Automatic Revert

on:
  issue_comment:
    types:
      - created

jobs:
  revert-commit:
    runs-on: ubuntu-20.04

    if: contains(github.event.comment.body, 'revert')

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Git 1
        run: git ${{github.event.comment.body}}