name: Automatic Revert

on:
  issue_comment:
    types:
      - created

jobs:
  revert-commit:
    runs-on: ubuntu-20.04

    if: contains(github.event.comment.body, '/revert')

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Git 1
        run: git config user.name “FernandoUNMSM"
      - name: Git 2
        run: git config user.email oscar.cabellos@unmsm.edu.pe
      - name: Git 3
        run: git config --global --add safe.directory /github/workspace
      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
